---
# tasks file for logwatch
#Logwatch Installation. 
   - name: Install LogWatch
     yum: name={{ item }} state=present update_cache=yes
     with_items:
     - logwatch
   - name: Sent address
     lineinfile: dest=/usr/share/logwatch/default.conf/logwatch.conf regexp=^MailTo line="MailTo = user@domain.com"
   - name: Mail Origin	
     lineinfile: dest=/usr/share/logwatch/default.conf/logwatch.conf regexp=^MailFrom line="MailFrom = Logwatch"
   - name: Range
     lineinfile: dest=/usr/share/logwatch/default.conf/logwatch.conf regexp=^Range line="Range = yesterday"
   - name: Reports in detail
     lineinfile: dest=/usr/share/logwatch/default.conf/logwatch.conf regexp=^Detail line="Detail = Low"
   - name: Services
     lineinfile: dest=/usr/share/logwatch/default.conf/logwatch.conf regexp=^Service line="Service = All"
   - name: Frequency
     lineinfile: dest=/usr/share/logwatch/default.conf/logwatch.conf regexp=^DailyReport line="DailyReport = yes"
   - name: Run LogWatch
     command: logwatch --detail Low --mailto username@domain.com --range yesterday
